# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Image-Magick-PixelMosaic
version:      0.03
version_from: lib/Image/Magick/PixelMosaic.pm
installdirs:  site
requires:
    Image::Magick:                 6.2.4

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30_01
